version: 2
updates:
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 5
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 5
