language: php
dist: trusty
sudo: false

php:
- 7.2
node_js:
- 10.9

env:
  global:
  - DRUPAL_BUILD_DIR=$TRAVIS_BUILD_DIR/../drupal

cache:
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
  - ~/.composer/cache

before_install:
- echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- phpenv config-rm xdebug.ini
- composer self-update

install:
- cd $TRAVIS_BUILD_DIR/docs && npm install -g vuepress
- composer create-project drupal-composer/drupal-project:8.x-dev $DRUPAL_BUILD_DIR --no-interaction
- cd $DRUPAL_BUILD_DIR
- composer remove drupal/core
- php -r "\$json = json_decode(file_get_contents('composer.json'), TRUE); \$json['repositories'][] = ['type' => 'path', 'url' => '$TRAVIS_BUILD_DIR' ]; file_put_contents('composer.json', json_encode(\$json, JSON_PRETTY_PRINT));"
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo $BRANCH
- composer require "amazeelabs/silverback:dev-$BRANCH"
- ./vendor/bin/silverback init
- source .envrc
- if [[ -n "$SB_JIRA_PROJECTS" ]]; then silverback download-tests; fi

script:
- silverback setup
- drush serve :8889 > log.txt 2>&1 &
  # Wait for drush serve to start up, but only for 20 seconds.
  - DRUSH_SERVE_WAIT=0
  - until netstat -an 2>/dev/null | grep '8889.*LISTEN'; \
      sleep 1; curl -I http://127.0.0.1:8889 \
      || DRUSH_SERVE_WAIT=$(($DRUSH_SERVE_WAIT + 1)) \
      && echo "Waited $DRUSH_SERVE_WAIT seconds for drush serve." \
      && (($DRUSH_SERVE_WAIT > 19)) ; \
      do true; done
- composer run-script run-tests --timeout 0
- cd $TRAVIS_BUILD_DIR/docs && npm run build
- kill $(jobs -p) || true

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: AmazeeLabs/silverback
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
