language: php
dist: xenial
sudo: false

php:
  - '7.2'

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ~/.composer/cache

addons:
  apt:
    packages:
      - libgconf-2-4

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - nvm install 10

install:
  - composer install
  - yarn install
  - source .envrc

script:
  - if [[ -n "$SB_JIRA_PROJECTS" ]]; then silverback download-tests; fi
  - |
    # The regex to get jira issue number from a git branch.
    regex='(.*)(^|/)([A-Z]+[A-Z0-9]?-[0-9]+)(.*)'
    # Get git branch.
    branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    # Get the jira issue number from branch name and add it to cypress tags. Or
    # run only completed tests.
    [[ $branch =~ $regex ]] && \
      export CYPRESS_TAGS="@${BASH_REMATCH[3]} or @COMPLETED" || \
      export CYPRESS_TAGS="@COMPLETED"
    echo "Going to run cypress with the following tags: $CYPRESS_TAGS"
    composer run-script run-tests

notifications:
  email: false

